INCLUDE_DIRECTORIES(
  mbed-os/targets/TARGET_STM/TARGET_STM32F4/device
  mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device
  mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE
  mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE
  mbed-os/targets/TARGET_STM/TARGET_STM32F4
  mbed-os/targets/TARGET_STM
  mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Source
  mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Include
  mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX/Config
  mbed-os/rtos/source/TARGET_CORTEX/rtx5/RTX
  mbed-os/rtos/source/TARGET_CORTEX/rtx5/Include
  mbed-os/rtos/source/TARGET_CORTEX/rtx5
  mbed-os/rtos/source/TARGET_CORTEX/rtx4
  mbed-os/rtos/source/TARGET_CORTEX
  mbed-os/rtos/source
  mbed-os/rtos
  mbed-os/platform/source/minimal-printf
  mbed-os/platform/source/TARGET_CORTEX_M
  mbed-os/platform/source
  mbed-os/platform/internal
  mbed-os/platform/cxxsupport
  mbed-os/platform
  mbed-os/hal/usb
  mbed-os/hal/storage_abstraction
  mbed-os/hal
  mbed-os/features/storage/system_storage
  mbed-os/features/storage/nvstore/source
  mbed-os/features/storage/nvstore
  mbed-os/features/storage/kvstore/tdbstore
  mbed-os/features/storage/kvstore/securestore
  mbed-os/features/storage/kvstore/kv_map
  mbed-os/features/storage/kvstore/include
  mbed-os/features/storage/kvstore/global_api
  mbed-os/features/storage/kvstore/filesystemstore
  mbed-os/features/storage/kvstore/direct_access_devicekey
  mbed-os/features/storage/kvstore/conf
  mbed-os/features/storage/kvstore
  mbed-os/features/storage/filesystem/littlefs/littlefs
  mbed-os/features/storage/filesystem/littlefs
  mbed-os/features/storage/filesystem/fat/ChaN
  mbed-os/features/storage/filesystem/fat
  mbed-os/features/storage/filesystem
  mbed-os/features/storage/blockdevice
  mbed-os/features/storage
  mbed-os/features/nfc/stack/transceiver/pn512
  mbed-os/features/nfc/stack/transceiver
  mbed-os/features/nfc/stack/tech/type4
  mbed-os/features/nfc/stack/tech/isodep
  mbed-os/features/nfc/stack/tech/iso7816
  mbed-os/features/nfc/stack/tech
  mbed-os/features/nfc/stack/platform
  mbed-os/features/nfc/stack/ndef
  mbed-os/features/nfc/stack
  mbed-os/features/nfc/nfc/ndef/common
  mbed-os/features/nfc/nfc/ndef
  mbed-os/features/nfc/nfc
  mbed-os/features/nfc/controllers
  mbed-os/features/nfc/acore/acore
  mbed-os/features/nfc/acore
  mbed-os/features/nfc
  mbed-os/features/netsocket/ppp/include/polarssl
  mbed-os/features/netsocket/ppp/include
  mbed-os/features/netsocket/ppp
  mbed-os/features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4
  mbed-os/features/netsocket/emac-drivers/TARGET_STM
  mbed-os/features/netsocket/cellular
  mbed-os/features/netsocket
  mbed-os/features/nanostack/sal-stack-nanostack/source/libNET/src
  mbed-os/features/nanostack/sal-stack-nanostack/source/libNET
  mbed-os/features/nanostack/sal-stack-nanostack/source/libDHCPv6
  mbed-os/features/nanostack/sal-stack-nanostack/source/ipv6_stack
  mbed-os/features/nanostack/sal-stack-nanostack/source/configs/base
  mbed-os/features/nanostack/sal-stack-nanostack/source/configs
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/whiteboard
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/utils
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/pan_blacklist
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/nist_aes_kw
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/nd_proxy
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/stack
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/serial
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/poll
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/mdns
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/dns
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/cpu
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/compiler
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/mac_neighbor_table
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/load_balance
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/ieee_802_11
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/hmac
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/fnv_hash
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/etx
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/blacklist
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/Trickle
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs/Neighbor_cache
  mbed-os/features/nanostack/sal-stack-nanostack/source/Service_Libs
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/key_sec_prot
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/protocols
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/kmp
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/eapol
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/TLS
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/PANA
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security/Common
  mbed-os/features/nanostack/sal-stack-nanostack/source/Security
  mbed-os/features/nanostack/sal-stack-nanostack/source/RPL
  mbed-os/features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/Include
  mbed-os/features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE
  mbed-os/features/nanostack/sal-stack-nanostack/source/MPL
  mbed-os/features/nanostack/sal-stack-nanostack/source/MLE
  mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/virtual_rf
  mbed-os/features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4
  mbed-os/features/nanostack/sal-stack-nanostack/source/MAC
  mbed-os/features/nanostack/sal-stack-nanostack/source/DHCPv6_client
  mbed-os/features/nanostack/sal-stack-nanostack/source/DHCPv6_Server
  mbed-os/features/nanostack/sal-stack-nanostack/source/Core/include
  mbed-os/features/nanostack/sal-stack-nanostack/source/Core
  mbed-os/features/nanostack/sal-stack-nanostack/source/Common_Protocols
  mbed-os/features/nanostack/sal-stack-nanostack/source/BorderRouter
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/NVM
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/ND
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Mesh
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Fragmentation
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps
  mbed-os/features/nanostack/sal-stack-nanostack/source/6LoWPAN
  mbed-os/features/nanostack/sal-stack-nanostack/source
  mbed-os/features/nanostack/sal-stack-nanostack/nanostack/platform
  mbed-os/features/nanostack/sal-stack-nanostack/nanostack
  mbed-os/features/nanostack/sal-stack-nanostack-eventloop/source
  mbed-os/features/nanostack/sal-stack-nanostack-eventloop/nanostack-event-loop/platform
  mbed-os/features/nanostack/sal-stack-nanostack-eventloop/nanostack-event-loop
  mbed-os/features/nanostack/sal-stack-nanostack-eventloop
  mbed-os/features/nanostack/sal-stack-nanostack
  mbed-os/features/nanostack/nanostack-interface
  mbed-os/features/nanostack/nanostack-hal-mbed-cmsis-rtos
  mbed-os/features/nanostack/mbed-mesh-api/source/include
  mbed-os/features/nanostack/mbed-mesh-api/source
  mbed-os/features/nanostack/mbed-mesh-api/mbed-mesh-api
  mbed-os/features/nanostack/mbed-mesh-api
  mbed-os/features/nanostack/coap-service/source/include
  mbed-os/features/nanostack/coap-service/source
  mbed-os/features/nanostack/coap-service/coap-service
  mbed-os/features/nanostack/coap-service
  mbed-os/features/nanostack
  mbed-os/features/mbedtls/targets/TARGET_STM/TARGET_STM32F4
  mbed-os/features/mbedtls/targets/TARGET_STM
  mbed-os/features/mbedtls/platform/inc
  mbed-os/features/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/COMPONENT_NSPE
  mbed-os/features/mbedtls/platform/COMPONENT_PSA_SRV_IMPL
  mbed-os/features/mbedtls/platform
  mbed-os/features/mbedtls/inc/psa
  mbed-os/features/mbedtls/inc/mbedtls
  mbed-os/features/mbedtls/inc
  mbed-os/features/mbedtls
  mbed-os/features/lwipstack/lwip/src/include/netif
  mbed-os/features/lwipstack/lwip/src/include/lwip/prot
  mbed-os/features/lwipstack/lwip/src/include/lwip/priv
  mbed-os/features/lwipstack/lwip/src/include/lwip
  mbed-os/features/lwipstack/lwip/src/include/compat/posix/sys
  mbed-os/features/lwipstack/lwip/src/include/compat/posix/net
  mbed-os/features/lwipstack/lwip/src/include/compat/posix/arpa
  mbed-os/features/lwipstack/lwip/src/include/compat/posix
  mbed-os/features/lwipstack/lwip/src/include/compat
  mbed-os/features/lwipstack/lwip/src/include
  mbed-os/features/lwipstack/lwip/src
  mbed-os/features/lwipstack/lwip-sys/arch
  mbed-os/features/lwipstack/lwip-sys
  mbed-os/features/lwipstack/lwip
  mbed-os/features/lwipstack
  mbed-os/features/lorawan/system
  mbed-os/features/lorawan/lorastack/phy
  mbed-os/features/lorawan/lorastack/mac
  mbed-os/features/lorawan/lorastack
  mbed-os/features/lorawan
  mbed-os/features/frameworks/utest/utest
  mbed-os/features/frameworks/utest
  mbed-os/features/frameworks/unity/unity
  mbed-os/features/frameworks/unity
  mbed-os/features/frameworks/nanostack-libservice/mbed-client-libservice/platform
  mbed-os/features/frameworks/nanostack-libservice/mbed-client-libservice
  mbed-os/features/frameworks/nanostack-libservice
  mbed-os/features/frameworks/mbed-trace/mbed-trace
  mbed-os/features/frameworks/mbed-trace
  mbed-os/features/frameworks/mbed-coap/source/include
  mbed-os/features/frameworks/mbed-coap/source
  mbed-os/features/frameworks/mbed-coap/mbed-coap
  mbed-os/features/frameworks/mbed-coap
  mbed-os/features/frameworks/mbed-client-randlib/mbed-client-randlib/platform
  mbed-os/features/frameworks/mbed-client-randlib/mbed-client-randlib
  mbed-os/features/frameworks/mbed-client-randlib
  mbed-os/features/frameworks/mbed-client-cli/mbed-client-cli
  mbed-os/features/frameworks/mbed-client-cli
  mbed-os/features/frameworks/greentea-client/greentea-client
  mbed-os/features/frameworks/greentea-client
  mbed-os/features/frameworks
  mbed-os/features/device_key/source
  mbed-os/features/device_key
  mbed-os/features/cellular/framework/targets/UBLOX/PPP
  mbed-os/features/cellular/framework/targets/UBLOX/N2XX
  mbed-os/features/cellular/framework/targets/UBLOX/AT
  mbed-os/features/cellular/framework/targets/UBLOX
  mbed-os/features/cellular/framework/targets/TELIT/ME910
  mbed-os/features/cellular/framework/targets/TELIT/HE910
  mbed-os/features/cellular/framework/targets/TELIT
  mbed-os/features/cellular/framework/targets/RiotMicro/AT
  mbed-os/features/cellular/framework/targets/RiotMicro
  mbed-os/features/cellular/framework/targets/QUECTEL/UG96
  mbed-os/features/cellular/framework/targets/QUECTEL/M26
  mbed-os/features/cellular/framework/targets/QUECTEL/EC2X
  mbed-os/features/cellular/framework/targets/QUECTEL/BG96
  mbed-os/features/cellular/framework/targets/QUECTEL/BC95
  mbed-os/features/cellular/framework/targets/QUECTEL
  mbed-os/features/cellular/framework/targets/MultiTech/DragonflyNano/PPP
  mbed-os/features/cellular/framework/targets/MultiTech/DragonflyNano
  mbed-os/features/cellular/framework/targets/MultiTech
  mbed-os/features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP
  mbed-os/features/cellular/framework/targets/GENERIC
  mbed-os/features/cellular/framework/targets/GEMALTO/CINTERION
  mbed-os/features/cellular/framework/targets/GEMALTO
  mbed-os/features/cellular/framework/targets/Altair/ALT1250/PPP
  mbed-os/features/cellular/framework/targets/Altair/ALT1250
  mbed-os/features/cellular/framework/targets/Altair
  mbed-os/features/cellular/framework/targets
  mbed-os/features/cellular/framework/device
  mbed-os/features/cellular/framework/common
  mbed-os/features/cellular/framework/AT
  mbed-os/features/cellular/framework/API
  mbed-os/features/cellular/framework
  mbed-os/features/cellular
  mbed-os/features
  mbed-os/events/internal
  mbed-os/events
  mbed-os/drivers/internal
  mbed-os/drivers
  mbed-os/components/wifi/esp8266-driver/ESP8266
  mbed-os/components/wifi/esp8266-driver
  mbed-os/components/wifi
  mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver
  mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver/source
  mbed-os/components/802.15.4_RF/stm-s2lp-rf-driver
  mbed-os/components/802.15.4_RF/mcr20a-rf-driver/source
  mbed-os/components/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver
  mbed-os/components/802.15.4_RF/mcr20a-rf-driver
  mbed-os/components/802.15.4_RF/atmel-rf-driver/source
  mbed-os/components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver
  mbed-os/components/802.15.4_RF/atmel-rf-driver
  mbed-os/components/802.15.4_RF
  mbed-os/components
  mbed-os/cmsis/TARGET_CORTEX_M
  mbed-os/cmsis
  mbed-os
  )
